"""Markdown report generator."""

from datetime import date, datetime
from pathlib import Path
from typing import Optional

from rich.console import Console

console = Console()


class ReportGenerator:
    """Generate Markdown reports from articles."""

    def __init__(self):
        pass

    def generate(
        self,
        articles_by_journal: dict,
        start_date: date,
        end_date: date,
        output_path: Optional[Path] = None,
        title: Optional[str] = None,
    ) -> str:
        """
        Generate a Markdown report.

        Args:
            articles_by_journal: Dict mapping journal names to article lists
            start_date: Report start date
            end_date: Report end date
            output_path: Path to save the report
            title: Report title

        Returns:
            Generated Markdown content
        """
        # Build markdown
        lines = []

        # Title
        if title:
            lines.append(f"# {title}")
        else:
            lines.append(f"# 学术论文聚合报告")

        lines.append(f"")
        lines.append(f"**时间范围:** {start_date} ~ {end_date}")
        lines.append(f"**生成时间:** {datetime.now().strftime('%Y-%m-%d %H:%M')}")
        lines.append(f"")

        # Summary
        total_articles = sum(len(articles) for articles in articles_by_journal.values())
        lines.append(f"**共收录:** {total_articles} 篇论文，来自 {len(articles_by_journal)} 个期刊")
        lines.append(f"")

        # Table of contents
        lines.append("## 目录")
        lines.append("")
        for journal_name, articles in articles_by_journal.items():
            anchor = self._make_anchor(journal_name)
            lines.append(f"- [{journal_name}](#{anchor}) ({len(articles)}篇)")
        lines.append("")
        lines.append("---")
        lines.append("")

        # Articles by journal
        for journal_name, articles in articles_by_journal.items():
            lines.append(f"## {journal_name}")
            lines.append("")

            for i, article in enumerate(articles, 1):
                lines.extend(self._format_article(article, i))
                lines.append("")

            lines.append("---")
            lines.append("")

        # Footer
        lines.append("")
        lines.append("---")
        lines.append("")
        lines.append("*Generated by [Paperflow](https://github.com/paperflow)*")

        content = "\n".join(lines)

        # Save to file if path provided
        if output_path:
            output_path = Path(output_path)
            output_path.write_text(content, encoding="utf-8")
            console.print(f"[green]Report saved to: {output_path}[/green]")

        return content

    def _format_article(self, article, index: int) -> list[str]:
        """Format a single article."""
        lines = []

        # Title (numbered)
        lines.append(f"### {index}. {article.title}")

        # Chinese title if available
        if article.title_zh:
            lines.append(f"**译名:** {article.title_zh}")

        lines.append("")

        # Authors and affiliations
        if article.authors:
            authors_str = ", ".join(article.authors[:10])  # Limit to 10 authors
            if len(article.authors) > 10:
                authors_str += f" et al. ({len(article.authors)} authors)"
            lines.append(f"**作者:** {authors_str}")

        if article.affiliations:
            aff_str = ", ".join(article.affiliations[:3])  # Limit to 3 affiliations
            if len(article.affiliations) > 3:
                aff_str += " ..."
            lines.append(f"**机构:** {aff_str}")

        # Publication date
        if article.published_date:
            lines.append(f"**发布时间:** {article.published_date}")

        # DOI
        if article.doi:
            lines.append(f"**DOI:** [{article.doi}](https://doi.org/{article.doi})")

        lines.append("")

        # Abstract
        if article.abstract:
            lines.append("**摘要 (Abstract):**")
            lines.append(f"> {article.abstract[:500]}{'...' if len(article.abstract) > 500 else ''}")
            lines.append("")

        # Chinese abstract
        if article.abstract_zh:
            lines.append("**摘要译文:**")
            lines.append(f"> {article.abstract_zh}")
            lines.append("")

        # AI Summary
        if article.summary:
            lines.append("**🤖 AI总结:**")
            lines.append(f"> {article.summary}")
            lines.append("")

        # Links
        links = []
        if article.url:
            links.append(f"[原文]({article.url})")
        if article.pdf_url:
            links.append(f"[PDF]({article.pdf_url})")
        if article.doi:
            links.append(f"[DOI](https://doi.org/{article.doi})")

        if links:
            lines.append(f"**链接:** {' | '.join(links)}")

        lines.append("")
        lines.append("---")
        lines.append("")

        return lines

    def _make_anchor(self, text: str) -> str:
        """Create a markdown anchor from text."""
        # Simple anchor generation
        anchor = text.lower()
        anchor = anchor.replace(" ", "-")
        anchor = "".join(c for c in anchor if c.isalnum() or c == "-")
        return anchor
